# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_PB.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_PB(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(707, 472)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/structure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QPushButton{\n"
"color:rgb(255, 0, 0);\n"
"font: 12pt \"宋体\";\n"
"}\n"
"\n"
"QLabel{\n"
"color:rgb(0, 85, 255);\n"
"font: 12pt \"宋体\";\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:rgb(0, 85, 255);\n"
"font: 12pt \"宋体\";\n"
"}\n"
"\n"
"QGroupBox{\n"
"color:rgb(170, 85, 255);\n"
"font: 12pt \"宋体\";\n"
"}\n"
"\n"
"QTextBrowser{\n"
"font: 12pt \"宋体\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"font: 12pt \"宋体\";\n"
"}\n"
"\n"
"QComboBox{\n"
"font: 12pt \"宋体\";\n"
"}\n"
"\n"
"QTextEdit{\n"
"font: 12pt \"宋体\";\n"
"}\n"
"\n"
"QSpinBox{\n"
"color:rgb(0, 85, 255);\n"
"font: 12pt \"宋体\";\n"
"}\n"
"\n"
"QRadioButton{\n"
"color:rgb(0, 85, 255);\n"
"font: 12pt \"宋体\";\n"
"}")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(164, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setReadOnly(False)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_18.addWidget(self.lineEdit_16)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_10.addWidget(self.lineEdit_9)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_6.addWidget(self.lineEdit_6)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_7.addWidget(self.lineEdit_7)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_8.addWidget(self.lineEdit_8)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(8, 1)
        self.verticalLayout.setStretch(9, 1)
        self.horizontalLayout_31.addWidget(self.groupBox)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_12.setText("")
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setPlaceholderText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_16.addWidget(self.lineEdit_12)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 1)
        self.horizontalLayout_16.setStretch(2, 3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_28.addWidget(self.label_14)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_15.setText("")
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setPlaceholderText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_28.addWidget(self.lineEdit_15)
        self.horizontalLayout_28.setStretch(0, 1)
        self.horizontalLayout_28.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_29.addWidget(self.label_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setPlaceholderText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_29.addWidget(self.lineEdit_17)
        self.horizontalLayout_29.setStretch(0, 2)
        self.horizontalLayout_29.setStretch(1, 3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_30.addWidget(self.label_17)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem2)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setPlaceholderText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_30.addWidget(self.lineEdit_18)
        self.horizontalLayout_30.setStretch(0, 1)
        self.horizontalLayout_30.setStretch(1, 1)
        self.horizontalLayout_30.setStretch(2, 3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_11.addWidget(self.checkBox)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_3.setStyleSheet("background-color:#0055ff")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_11.addWidget(self.pushButton_3)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_11.addWidget(self.lineEdit_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_12.addWidget(self.checkBox_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_4.setStyleSheet("background-color:#ff0000")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_12.addWidget(self.pushButton_4)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_12.addWidget(self.lineEdit_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_13.addWidget(self.checkBox_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_5.setStyleSheet("background-color:#00aa00")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_13.addWidget(self.pushButton_5)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_13.addWidget(self.lineEdit_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_14.addWidget(self.checkBox_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_6.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_6.setStyleSheet("background-color:#5500ff")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_14.addWidget(self.pushButton_6)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_14.addWidget(self.lineEdit_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_26.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_15.addWidget(self.checkBox_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_7.setStyleSheet("background-color:#aa5500")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_15.addWidget(self.pushButton_7)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_19.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_15.addWidget(self.lineEdit_19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_19.addWidget(self.checkBox_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_8.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_8.setStyleSheet("background-color:#aa55ff")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_19.addWidget(self.pushButton_8)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_19.addWidget(self.lineEdit_20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_20.addWidget(self.checkBox_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_9.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_9.setStyleSheet("background-color:#ff5500")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_20.addWidget(self.pushButton_9)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_20.addWidget(self.lineEdit_21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_26.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_21.addWidget(self.checkBox_8)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_10.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_10.setStyleSheet("background-color:#ff557f")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_21.addWidget(self.pushButton_10)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_21.addWidget(self.lineEdit_22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_22.addWidget(self.checkBox_9)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_11.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_11.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_11.setStyleSheet("background-color:#55aa7f")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_22.addWidget(self.pushButton_11)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_22.addWidget(self.lineEdit_23)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_23.addWidget(self.checkBox_10)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_12.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_12.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_12.setStyleSheet("background-color:#aaaa7f")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_23.addWidget(self.pushButton_12)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_23.addWidget(self.lineEdit_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_24.addWidget(self.checkBox_11)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_13.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_13.setStyleSheet("background-color:#ffaa7f")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_24.addWidget(self.pushButton_13)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_24.addWidget(self.lineEdit_25)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_25.addWidget(self.checkBox_12)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_14.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_14.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButton_14.setStyleSheet("background-color:#ffff7f")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_25.addWidget(self.pushButton_14)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(20, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_25.addWidget(self.lineEdit_26)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_26.addWidget(self.groupBox_4)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_26)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_9.addWidget(self.radioButton)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(17, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem4 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_17.addWidget(self.pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_31.addLayout(self.verticalLayout_8)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit, self.lineEdit_16)
        Dialog.setTabOrder(self.lineEdit_16, self.lineEdit_9)
        Dialog.setTabOrder(self.lineEdit_9, self.lineEdit_2)
        Dialog.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Dialog.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        Dialog.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        Dialog.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        Dialog.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        Dialog.setTabOrder(self.lineEdit_8, self.lineEdit_12)
        Dialog.setTabOrder(self.lineEdit_12, self.lineEdit_15)
        Dialog.setTabOrder(self.lineEdit_15, self.lineEdit_17)
        Dialog.setTabOrder(self.lineEdit_17, self.lineEdit_18)
        Dialog.setTabOrder(self.lineEdit_18, self.checkBox)
        Dialog.setTabOrder(self.checkBox, self.checkBox_2)
        Dialog.setTabOrder(self.checkBox_2, self.checkBox_3)
        Dialog.setTabOrder(self.checkBox_3, self.checkBox_4)
        Dialog.setTabOrder(self.checkBox_4, self.checkBox_5)
        Dialog.setTabOrder(self.checkBox_5, self.checkBox_6)
        Dialog.setTabOrder(self.checkBox_6, self.checkBox_7)
        Dialog.setTabOrder(self.checkBox_7, self.checkBox_8)
        Dialog.setTabOrder(self.checkBox_8, self.checkBox_9)
        Dialog.setTabOrder(self.checkBox_9, self.checkBox_10)
        Dialog.setTabOrder(self.checkBox_10, self.checkBox_11)
        Dialog.setTabOrder(self.checkBox_11, self.checkBox_12)
        Dialog.setTabOrder(self.checkBox_12, self.lineEdit_10)
        Dialog.setTabOrder(self.lineEdit_10, self.lineEdit_11)
        Dialog.setTabOrder(self.lineEdit_11, self.lineEdit_13)
        Dialog.setTabOrder(self.lineEdit_13, self.lineEdit_14)
        Dialog.setTabOrder(self.lineEdit_14, self.lineEdit_19)
        Dialog.setTabOrder(self.lineEdit_19, self.lineEdit_20)
        Dialog.setTabOrder(self.lineEdit_20, self.lineEdit_21)
        Dialog.setTabOrder(self.lineEdit_21, self.lineEdit_22)
        Dialog.setTabOrder(self.lineEdit_22, self.lineEdit_23)
        Dialog.setTabOrder(self.lineEdit_23, self.lineEdit_24)
        Dialog.setTabOrder(self.lineEdit_24, self.lineEdit_25)
        Dialog.setTabOrder(self.lineEdit_25, self.lineEdit_26)
        Dialog.setTabOrder(self.lineEdit_26, self.radioButton)
        Dialog.setTabOrder(self.radioButton, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.pushButton_5)
        Dialog.setTabOrder(self.pushButton_5, self.pushButton_6)
        Dialog.setTabOrder(self.pushButton_6, self.pushButton_7)
        Dialog.setTabOrder(self.pushButton_7, self.pushButton_8)
        Dialog.setTabOrder(self.pushButton_8, self.pushButton_9)
        Dialog.setTabOrder(self.pushButton_9, self.pushButton_10)
        Dialog.setTabOrder(self.pushButton_10, self.pushButton_11)
        Dialog.setTabOrder(self.pushButton_11, self.pushButton_12)
        Dialog.setTabOrder(self.pushButton_12, self.pushButton_13)
        Dialog.setTabOrder(self.pushButton_13, self.pushButton_14)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PB parameter input"))
        self.groupBox.setTitle(_translate("Dialog", "Parameter input"))
        self.label.setText(_translate("Dialog", "Fermi level"))
        self.lineEdit.setToolTip(_translate("Dialog", "<html><head/><body><p>grep fermi OUTCAR</p><p>填入E-fermi</p></body></html>"))
        self.lineEdit.setText(_translate("Dialog", "-3.0637"))
        self.label_9.setText(_translate("Dialog", "eV"))
        self.label_15.setText(_translate("Dialog", "High symmetry point"))
        self.lineEdit_16.setToolTip(_translate("Dialog", "高对称点个数"))
        self.lineEdit_16.setText(_translate("Dialog", "3"))
        self.label_10.setText(_translate("Dialog", "Radius scaling factor"))
        self.lineEdit_9.setToolTip(_translate("Dialog", "每一个点的比例缩放因子"))
        self.lineEdit_9.setText(_translate("Dialog", "150"))
        self.label_2.setText(_translate("Dialog", "X min"))
        self.lineEdit_2.setToolTip(_translate("Dialog", "系统默认取横坐标最小值"))
        self.label_3.setText(_translate("Dialog", "X max"))
        self.lineEdit_3.setToolTip(_translate("Dialog", "系统默认取横坐标最大值"))
        self.label_4.setText(_translate("Dialog", "Y min"))
        self.lineEdit_4.setToolTip(_translate("Dialog", "纵坐标刻度最小值"))
        self.lineEdit_4.setText(_translate("Dialog", "-4"))
        self.label_5.setText(_translate("Dialog", "Y max"))
        self.lineEdit_5.setToolTip(_translate("Dialog", "纵坐标刻度最大值"))
        self.lineEdit_5.setText(_translate("Dialog", "4"))
        self.label_6.setText(_translate("Dialog", "X label"))
        self.lineEdit_6.setToolTip(_translate("Dialog", "默认不输入"))
        self.label_7.setText(_translate("Dialog", "Y label"))
        self.lineEdit_7.setToolTip(_translate("Dialog", "纵坐标标签"))
        self.lineEdit_7.setText(_translate("Dialog", "Energy(eV)"))
        self.label_8.setText(_translate("Dialog", "Title"))
        self.lineEdit_8.setToolTip(_translate("Dialog", "图标题"))
        self.groupBox_6.setTitle(_translate("Dialog", "Atom selection"))
        self.label_13.setText(_translate("Dialog", "Atom number:"))
        self.label_14.setText(_translate("Dialog", "Atom name:"))
        self.label_16.setText(_translate("Dialog", "X scaling factor:"))
        self.lineEdit_17.setToolTip(_translate("Dialog", "2表示取1/2的k点数"))
        self.lineEdit_17.setText(_translate("Dialog", "2"))
        self.label_17.setText(_translate("Dialog", "Atom subscript:"))
        self.lineEdit_18.setToolTip(_translate("Dialog", "PROCAR第9行第一个原子下标为0"))
        self.lineEdit_18.setText(_translate("Dialog", "0"))
        self.groupBox_5.setTitle(_translate("Dialog", "Orbit selection"))
        self.groupBox_2.setTitle(_translate("Dialog", "total"))
        self.checkBox.setText(_translate("Dialog", "s"))
        self.lineEdit_10.setText(_translate("Dialog", "6"))
        self.checkBox_2.setText(_translate("Dialog", "p"))
        self.lineEdit_11.setText(_translate("Dialog", "2"))
        self.checkBox_3.setText(_translate("Dialog", "d"))
        self.lineEdit_13.setText(_translate("Dialog", "7"))
        self.checkBox_4.setText(_translate("Dialog", "tot"))
        self.lineEdit_14.setText(_translate("Dialog", "1"))
        self.groupBox_3.setTitle(_translate("Dialog", "p orbit"))
        self.checkBox_5.setText(_translate("Dialog", "p_y"))
        self.lineEdit_19.setText(_translate("Dialog", "3"))
        self.checkBox_6.setText(_translate("Dialog", "p_z"))
        self.lineEdit_20.setText(_translate("Dialog", "4"))
        self.checkBox_7.setText(_translate("Dialog", "p_x"))
        self.lineEdit_21.setText(_translate("Dialog", "5"))
        self.groupBox_4.setTitle(_translate("Dialog", "d orbit"))
        self.checkBox_8.setText(_translate("Dialog", "d_xy"))
        self.lineEdit_22.setText(_translate("Dialog", "8"))
        self.checkBox_9.setText(_translate("Dialog", "d_yz"))
        self.lineEdit_23.setText(_translate("Dialog", "9"))
        self.checkBox_10.setText(_translate("Dialog", "d_z2"))
        self.lineEdit_24.setText(_translate("Dialog", "10"))
        self.checkBox_11.setText(_translate("Dialog", "d_xz"))
        self.lineEdit_25.setText(_translate("Dialog", "11"))
        self.checkBox_12.setText(_translate("Dialog", "d_x2"))
        self.lineEdit_26.setText(_translate("Dialog", "12"))
        self.radioButton.setToolTip(_translate("Dialog", "暂未完善"))
        self.radioButton.setText(_translate("Dialog", "Whether to draw the orbitals separately"))
        self.pushButton_2.setText(_translate("Dialog", "Curve color"))
        self.pushButton.setText(_translate("Dialog", "Plot"))

