from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QHeaderView


class Ui_Lattice(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(456, 718)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/structure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QPushButton{\ncolor:rgb(0, 85, 255);\nfont: 12pt \"Times New Roman\";\n}\n\n"
                           "QLabel{\ncolor:rgb(0, 85, 255);\nfont: 12pt \"Times New Roman\";\n}\n\n"
                           "QCheckBox{\ncolor:rgb(0, 85, 255);\nfont: 12pt \"Times New Roman\";\n}\n\n"
                           "QGroupBox{\ncolor:rgb(0, 85, 255);\nfont: 12pt \"Times New Roman\";\n}\n\n"
                           "QTextBrowser{\nfont: 12pt \"Times New Roman\";\n}\n\n"
                           "QLineEdit{\nfont: 12pt \"Times New Roman\";\n}\n\n"
                           "QTabWidget{\ncolor:rgb(0, 85, 255);\nfont: 12pt \"Times New Roman\";\n}\n\n"
                           "QRadioButton{\ncolor:rgb(0, 85, 255);\nfont: 12pt \"Times New Roman\";\n}\n\n"
                           "QTabWidget{\ncolor:rgb(0, 85, 255);\nfont: 12pt \"Times New Roman\";\n}\n"
                           "")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 1)
        self.horizontalLayout_11.setStretch(2, 4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_8.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_8.addWidget(self.radioButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setMinimumSize(QtCore.QSize(55, 0))
        self.label_8.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_4.addWidget(self.lineEdit_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setMinimumSize(QtCore.QSize(55, 0))
        self.label_9.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_5.addWidget(self.lineEdit_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setMinimumSize(QtCore.QSize(55, 0))
        self.label_10.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_6.addWidget(self.lineEdit_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 0, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_12.setEnabled(False)
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 0, 1, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 0, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_14.setEnabled(False)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 1, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_15.setEnabled(False)
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 1, 1, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_16.setEnabled(False)
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 1, 2, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_17.setEnabled(False)
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 2, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_18.setEnabled(False)
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout.addWidget(self.lineEdit_18, 2, 1, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_19.setEnabled(False)
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout.addWidget(self.lineEdit_19, 2, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_9.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_9.addWidget(self.radioButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_6)

        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 3, item)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)

        # Restrict the lineEdit edit box can only enter characters and numbers
        reg = QRegExp('[a-zA-z0-9]+$')
        validator = QRegExpValidator(reg, self.lineEdit)
        self.lineEdit.setValidator(validator)
        # The horizontal direction label expands the remaining part of the window and fills the form
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        # In the horizontal direction, the table size is expanded to an appropriate size
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        self.retranslateUi(Form)
        self.radioButton.toggled['bool'].connect(self.lineEdit_2.setEnabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_3.setEnabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_4.setEnabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_8.setEnabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_9.setEnabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_10.setEnabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_11.setDisabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_12.setDisabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_13.setDisabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_14.setDisabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_15.setDisabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_16.setDisabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_17.setDisabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_18.setDisabled)
        self.radioButton.toggled['bool'].connect(self.lineEdit_19.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lattice parameter input"))
        self.label.setText(_translate("Form", "Space group："))
        self.groupBox.setTitle(_translate("Form", "Lattice input"))
        self.label_11.setText(_translate("Form", "Choose lattice input method："))
        self.radioButton.setText(_translate("Form", "coordinate"))
        self.radioButton_2.setText(_translate("Form", "matrix"))
        self.groupBox_4.setTitle(_translate("Form", "coordinate"))
        self.groupBox_2.setTitle(_translate("Form", "length"))
        self.label_2.setText(_translate("Form", "a："))
        self.label_3.setText(_translate("Form", "b："))
        self.label_4.setText(_translate("Form", "c："))
        self.groupBox_3.setTitle(_translate("Form", "angle"))
        self.label_8.setText(_translate("Form", "Alpha："))
        self.label_9.setText(_translate("Form", "Beta："))
        self.label_10.setText(_translate("Form", "Gamma："))
        self.groupBox_5.setTitle(_translate("Form", "matrix"))
        self.lineEdit_11.setText(_translate("Form", "0"))
        self.lineEdit_12.setText(_translate("Form", "0"))
        self.lineEdit_13.setText(_translate("Form", "0"))
        self.lineEdit_14.setText(_translate("Form", "0"))
        self.lineEdit_15.setText(_translate("Form", "0"))
        self.lineEdit_16.setText(_translate("Form", "0"))
        self.lineEdit_17.setText(_translate("Form", "0"))
        self.lineEdit_18.setText(_translate("Form", "0"))
        self.lineEdit_19.setText(_translate("Form", "0"))
        self.label_12.setText(_translate("Form", "Select the coordinate input method："))
        self.radioButton_4.setText(_translate("Form", "Fractional"))
        self.radioButton_3.setText(_translate("Form", "Cartesian"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Element ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "x"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "y"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "z"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Form", "Add"))
        self.pushButton_4.setText(_translate("Form", "Remove"))
        self.pushButton_3.setText(_translate("Form", "Clear"))
        self.pushButton_2.setText(_translate("Form", "Enter"))
